### ISSUE TITLE
Help Regarding .env template 

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/elyzen#11]
Hey @codeblitz97 @avalynndev can u guys help me with the `.env` template. as mentioned in the Readme of the project the env file is not there.
so can u help with this n where to find the Required API to Run the project.

**Comment by sulvii** [comment]
REDIS_URI = OPTIONAL (Remove this if you don't want to use it)
NEXT_PUBLIC_DOMAIN = http://localhost:3000 (your domain name)
CONSUMET_API = (consumet api: https://github.com/consumet/api.consumet.org)
HIANIME_API = (aniwatch-api: https://github.com/ghoshRitesh12/aniwatch-api)
MALSYNC_URI = https://api.malsync.moe/mal/anime/anilist:
NEXT_PUBLIC_CORS_PROXY_URL = https://corsproxy.io/
