### ISSUE TITLE
[Bug] Fix buttons trending & all time popular, [settings]

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/elyzen#18]
hey @codeblitz97 the buttons (trending & popular) are not working when clicked on them.
can u take a look at them.
and also i think settings is not yet implemented. if its implemented then the settings button is also not working nothing happens when u click o these 3 buttons.

**Comment by skgupta507** [comment]
also can i suggest that the button [home, theme selector, popular & trending] all these buttons be aligned in the centre instead og letting them have so much space.

**Comment by sulvii** [comment]
Adding it only center makes it look kinda ugly, I tried that

**Comment by skgupta507** [comment]
> Adding it only center makes it look kinda ugly, I tried that

something like this ........ in the below image.
![image](https://github.com/codeblitz97/elyzen/assets/131786207/34010d61-50e6-4d43-82f5-98b0047aebe7)

**Comment by sulvii** [comment]
I don't intend to copy from other UI since this UI may already exist in other site, so ignoring it

**Comment by skgupta507** [comment]
> I don't intend to copy from other UI since this UI may already exist in other site, so ignoring it

no no iam not saying u to copy the ui 
i was talking about the arrangement of the icons

**Comment by sulvii** [comment]
I did it

**Comment by avalynndev** [comment]
@codeblitz97 Can we close this as we added it?
