### ISSUE TITLE
Settings does not open

### ISSUE THREAD

**Issue by Drac1652** [codeblitz97/elyzen#22]
Am a new user to the website and i find it quite amazing, so i tried to open settings if there are option to login but settings does not open

**Comment by sulvii** [comment]
This thing is not yet implemented as it has some works to do with localstorage, I will add it today anyways

**Comment by avalynndev** [comment]
This website is still in development mode, if you wanna add tasks to make our website better send a comment at: #2

**Comment by avalynndev** [comment]
@codeblitz97 kindly close this

**Comment by Drac1652** [comment]
I think maybe right now the website is on development bcoz the homepage
shows only trending now and all time popular..
So i have few suggestions that u may add and the web will be cooler
1. Additional homepage categories like
    -popular this season
    -popular next season
    -current airing
    -recommend animes (this shall depend on individual most viewed anime
genre)

2. It'd be good if you add anilist or Mal sync, this will be advantagous to
people who have seen many anime and have a lot of them in watchlist, and
this will save time and prevent mannual selection

3. Anime info when playing the video. There should be anime info and image
to show which anime a person is watching and also relations should also
display when watching anime. (See the picture, the watchpage is almost
blank)

4. Additional feature is characters features it's fine to display just
below the relation category on the anime info page

**Comment by sulvii** [comment]
Anilist will be added, it's planned

Same goes for:
Currently Airing
Popular This Season
Popular Next Season
Recommended Anime
Upcoming Anime

**Comment by Drac1652** [comment]
Cool, thanks for the heads up!

**Comment by Drac1652** [comment]
Hellow, i was using  the website and i noticed that if you turn off the
hero trailer to play, the whole anime preview doesn't appear.
Can't you make if you turn off the trailer at least the anime background
image of poster image appears..
