### ISSUE TITLE
"Error on watch page"

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/elyzen#24]
hey @codeblitz97 sorry for disturbing but iam unable to play any episodes on my hosted instance due to the error _**Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 2933463156**_ 
when ever i click on any episode this message shows instead of the watchpage.
can u help me with fixing this issue.

**Comment by skgupta507** [comment]
vercel logs

[logs_result (3).json](https://github.com/user-attachments/files/15524487/logs_result.3.json)

and screenshot

![image](https://github.com/codeblitz97/elyzen/assets/131786207/fd21d095-914c-43e2-acb5-7ddf16fe3e07)

**Comment by sulvii** [comment]
Make sure your API is working

**Comment by skgupta507** [comment]
Iam using ur api

**Comment by sulvii** [comment]
Which anime is showing this error?

**Comment by sulvii** [comment]
Can I get the ID of that anime?

**Comment by skgupta507** [comment]
Iam getting that error on clicking any anime
Not any specific one

**Comment by sulvii** [comment]
Try reforking it

**Comment by skgupta507** [comment]
> Try reforking it

Done
And redeployed it but still getting the same issue

The episode url i tried opening. 
https://elyzenx.vercel.app/watch/153288?episodeId=kaiju-no-8-19145%3Fep%3D123344&provider=zoro&type=sub&number=1

**Comment by sulvii** [comment]
It's an issue with vercel, vercel is behaving weirdly

**Comment by skgupta507** [comment]
> It's an issue with vercel, vercel is behaving weirdly

I have it hosted on netlify and render also 
Even there iam getting the same issue

**Comment by avalynndev** [comment]
@codeblitz97 it is taking too long to fetch episodes of even a anime with only 12 episodes. I opned an anime i got Serveless Function once, and 2nd time got Timeout

**Comment by sulvii** [comment]
It shouldn't happen

**Comment by avalynndev** [comment]
@codeblitz97 as you are rebuilding the site, i think we can close this as of know.

**Comment by sulvii** [comment]
yes and also please avoid mentioning me
