### ISSUE TITLE
[Bug] Trending page logo & anime title misaligned.

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/elyzen#6]
hey @codeblitz97 @avalynndev I checked the site and found few bugs u can retify such as the Anime title on the trendings page (when the trending button is pressed) is misaligned and shows only half of the text and it is colliding with the Website Name.
i have attached SC below pls check it out.
![image](https://github.com/codeblitz97/elyzen/assets/131786207/009e3907-04aa-4a0f-973b-b264f56968bc)
if it is showing let it show full name or hide it completely so that only the trending animes shuld be visible.

**Comment by sulvii** [comment]
Just a regular issue with z-index
