### ISSUE TITLE
[Suggestions] Text (font) change

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/elyzen#7]
Hi Again @codeblitz97 @avalynndev Iam back again with one more Tip 
can u guys maybe change the text font of the Heading of TRENDING & ALL TIME POPULAR. Cause it doesnot match the websites UI / Design pattern.

**Comment by sulvii** [comment]
You are right

**Comment by avalynndev** [comment]
Point. I just thought it looks cool so I kept it

**Comment by skgupta507** [comment]
> Point. I just thought it looks cool so I kept it

That's why it's sticks out as a sore thumb 👍
It would've looked good if the whole site used the same font. 

But that's just my opinion it's ur project if it's to ur liking we have no issue. 🙂

**Comment by sulvii** [comment]
I was planning to abound this project but right now, experimenting with something new

**Comment by sulvii** [comment]
You can check it out: https://elyzen.vercel.app

**Comment by sulvii** [comment]
Also, fyi, I am not gonna prioritize this website, this is just a personal project so I can watch anime for myself. I don't have any intention to make this site public
